apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: nodejs
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
